// Capacitor Build Configurations
android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_21
      targetCompatibility JavaVersion.VERSION_21
  }
}

dependencies {
    implementation project(':capacitor-android')
    implementation project(':capacitor-splash-screen')
    implementation project(':capacitor-status-bar')
}

if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
